name: flutterfiretest
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  cloud_firestore: ^0.14.3
  provider: ^4.3.2+1

  carousel_slider: ^2.3.1
  curved_navigation_bar:
  flutter_slidable:
  flutter_tindercard: ^0.2.0
  email_validator: "^1.0.0"
  charts_flutter: ^0.9.0
  animated_splash_screen: ^1.0.1+2
  eva_icons_flutter:

  cupertino_icons: ^0.1.3
  cron: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brain-openmoji.png
